[package]
name = "visualization"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]
edition = "2018"

[dependencies]
nannou = "0.9"
#num-complex = "*"
chfft = "0.2.4"
#num-complex = ">=0.0.0"
num-complex = "0.1.43"
