[package]
name = "visualization"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]
edition = "2018"

[dependencies]
nannou = "0.9"
rand = "0.6.5"
clap = "2.33.0"
common = {path="../common"}
hilbert = {path="../hilbert"}
